# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-12-09 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181208_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
