# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-12-09 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181208_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student_status',
            field=models.CharField(choices=[('A', 'active'), ('G', 'Graduated'), ('M', 'Moved away'), ('N', 'No longer interested'), ('U', 'Undefined')], default='U', max_length=1),
        ),
    ]
