# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-12-10 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181209_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student_grade',
            field=models.CharField(choices=[('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('U', 'Undefined')], default='U', max_length=1),
        ),
    ]
