# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-12-09 18:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('Pu', 'Public'), ('Pi', 'Private'), ('Ho', 'Home School')], default='Pu', max_length=2),
        ),
    ]
