# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-12-09 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20181209_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved')], default='P', max_length=1),
        ),
    ]
