# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-12-09 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_application_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
