# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-12-09 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
