# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-12-09 22:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0006_delete_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Pu', 'Public'), ('Pi', 'Private'), ('Ho', 'Home School')], default='Pu', max_length=2)),
                ('school_name', models.CharField(default='', max_length=100)),
                ('grade', models.FloatField(max_length=4.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
