# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-12-10 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20150601_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('1', 'first week of June'), ('2', 'second week of June'), ('3', 'third week of June'), ('U', 'Undefined')], default='U', max_length=1)),
                ('section_time', models.CharField(choices=[('1', '9:45-11:15am'), ('2', '1:15-2:45pm'), ('U', 'Undefined')], default='U', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.CharField(choices=[('1', '4-5'), ('2', '6-8'), ('3', '9-12'), ('U', 'Undefined')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='TBA', max_length=255),
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
