# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-12-10 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20181209_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
