# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-12-10 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_take'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='course',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
